### ISSUE TITLE
Shader Error

### ISSUE THREAD

**Issue by brynfury** [kode80/kode80SSR#1]
Hi,
the preview looks great. I have an Shader error in 'kode80/SSR': incorrect number of arguments to numeric-type constructor at line 290 (on d3d11).
After build the hole scene is pink/magenta...

![kode80_issue](https://cloud.githubusercontent.com/assets/11438086/6614991/28f6f7d0-c8a0-11e4-9766-a768c643a9ce.png)

**Comment by kode80** [comment]
Thanks. I know exactly what this is (DX doesn't like numeric constructors without all params i.e. float4( 1.0) instead of float4( 1.0, 1.0, 1.0, 1.0)). I thought I'd fixed all of these (Unity stopped complaining and I got a Win build that worked on my Win machine) but I guess it's a specific version of DX. 
I'm going to go through and try and catch them all, then push.

**Comment by kode80** [comment]
Ok, I've pushed that fix. Please check that works for you when you get a chance and if so close the issue. Cheers!

**Comment by brynfury** [comment]
Yes... Works fine..! Thank you and great job...:)

**Comment by kode80** [comment]
Excellent, glad to hear it!
