### ISSUE TITLE
Broken In Build (Null Reference Exception)

### ISSUE THREAD

**Issue by KenzieMac130** [kode80/kode80SSR#4]
Kode80SSR Package as of 3/17/2015.
Unity 5.0.0f3 Pro
Nvidia 840M GPU, Intel Core i7 Quad

The Effect works perfectly fine inside the editor with no Errors (but I do get sending message header failed warning on build), but inside the in game Dev-Console it displays a bunch of generic Null Reference exceptions and the viewport is broken just returning an incomplete render pass with occasional flickering between normal pass.

![image](https://cloud.githubusercontent.com/assets/7585719/6701924/9e9d75e2-ccf9-11e4-94d2-9229265560b8.png)

Project Files for SSR are:
Assets/SSR/SSR.cs
Assets/SSR/ScreenResizeDetector.cs
Assets/SSR/Shaders/BackFaceDepth.shader
Assets/SSR/Shaders/BilateralBlur.shader
Assets/SSR/Shaders/DeferredTerrain.shader
Assets/SSR/Shaders/SSR.shader
Assets/SSR/Shaders/SSRBlurCombiner.shader

I used proper setup and have isolated the issue to the SSR component on the Main Camera, the SSR Scripts and Shaders are Un-modified and same as can be found in master.
Other Packages I used in my project:
-ShaderForge
-SSAO Pro

![image](https://cloud.githubusercontent.com/assets/7585719/6702083/5fb91658-ccfc-11e4-9f9e-bdc0fe229479.png)

**Comment by kode80** [comment]
Sounds like you may not have the SSR shaders in the resources folder. The SSR.cs script dynamically loads the appropriate shaders using Shader.Find() - for this to work they need to be in the /Resources folder so that Unity knows to include them in standalone builds (since they aren't referenced anywhere in the scene).

The three shaders required should be as follows:
/Resources/Shaders/SSR.shader
/Resources/Shaders/BilateralBlur.shader
/Resources/Shaders/SSRBlurCombiner.shader

Let me know if this fixes it.

**Comment by KenzieMac130** [comment]
Okay it works now, Thank You. I probably should have tried to directly imitate the file structure, but I guess I made the false assumption that if it loaded in the editor there shouldn't be a problem in the final build.

Can't go without this amazing effect!

**Comment by kode80** [comment]
Awesome!

**Comment by mendezwtf** [comment]
Kode80, you're awesome.  Thank you for making this great plugin open source :)
