### ISSUE TITLE
[Suggestion] Contribute to reflection probes buffer instead of blend manually

### ISSUE THREAD

**Issue by Rbn3D** [kode80/kode80SSR#6]
Hello, this is not a real issue but a suggestion.

I think command buffers feature in U5 could be used to paint reflected pixels directly on reflection probes buffer. This way you just let unity render materials and apply blur, etc. by itself.

I don't know if that is possible in the current rendering pipeline (I don't when the cubemaps are blended in the rendering queue, (docs are not clear)) and I don't know if would be feasible to alter cubemap buffer texture in screen space, but it would be nice if possible.

Thank you for efforts!

**Comment by kode80** [comment]
I've actually been looking into a similar approach, that is inserting the SSR process into the rendering pipeline so that reflections contribute to the overall lighting. While I haven't totally ruled it out yet, there are some pretty major points against this; SSR would only be able to use the albedo color which would mean you wouldn't get final material reflections and roughness blurring would still have to be handled separately which most likely would be more costly than the current implementation (reflection probes have their multiple blur levels baked - they're not blurred at runtime - try reflection probes that update at runtime to see you how costly this is).
